build.gradle
src/main/java/com/example/jobis/global/security/SecurityConfig.java
src/main/java/com/example/jobis/global/web/WebSecurityConfig.java
src/main/resources/application.yml

🔀 :: (#08) 시큐리티 설정

---

build.gradle
src/main/java/com/example/jobis/global/error/ErrorResponse.java
src/main/java/com/example/jobis/global/error/GlobalExceptionFilter.java
src/main/java/com/example/jobis/global/error/GlobalExceptionHandler.java
src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
src/main/java/com/example/jobis/global/error/exception/JobisException.java

- close #10
- ErrorCode, BaseException
- handler, filter handler

🔗 :: (#10)exception_handling

---

src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/controller/dto/request/CompanyDetailsRequest.java
src/main/java/com/example/jobis/domain/company/controller/dto/request/RegisterCompanyRequest.java
src/main/java/com/example/jobis/domain/company/domain/Company.java
src/main/java/com/example/jobis/domain/company/domain/CompanyDetails.java
src/main/java/com/example/jobis/domain/company/domain/repository/CompanyDetailsRepository.java
src/main/java/com/example/jobis/domain/company/domain/repository/CompanyRepository.java
src/main/java/com/example/jobis/domain/company/domain/type/Address.java
src/main/java/com/example/jobis/domain/company/domain/type/CompanyInfo.java
src/main/java/com/example/jobis/domain/company/domain/type/Contact.java
src/main/java/com/example/jobis/domain/company/domain/type/Manager.java
src/main/java/com/example/jobis/domain/company/exception/InvalidBusinessNumberException.java
src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java
src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponse.java
src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseBody.java
src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseHeader.java
src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseItem.java
src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseItems.java
src/main/java/com/example/jobis/infrastructure/resttemplate/facade/RestTemplateFacade.java
src/main/resources/application.yml

- close #14 
- 기업체 등록 api를 구현함

🧩 :: (#14) 기업체 등록 api 구현

---

src/main/java/com/example/jobis/JobisApplication.java
src/main/java/com/example/jobis/domain/company/domain/Company.java
src/main/java/com/example/jobis/global/entity/BaseTimeEntity.java
src/main/java/com/example/jobis/global/entity/User.java
src/main/java/com/example/jobis/global/enums/Authority.java
src/main/java/com/example/jobis/infrastructure/resttemplate/facade/RestTemplateFacade.java

- close #17
- 유저 엔티티 상속관계로 풀어줌
- 몇몇 에러 수정

🔗 :: (#17) 엔티티 매핑

---

src/main/java/com/example/jobis/JobisApplication.java
src/main/java/com/example/jobis/domain/auth/domain/RefreshToken.java
src/main/java/com/example/jobis/domain/auth/domain/repository/RefreshTokenRepository.java
src/main/java/com/example/jobis/domain/company/domain/Company.java
src/main/java/com/example/jobis/domain/company/domain/repository/CompanyRepository.java
src/main/java/com/example/jobis/domain/company/exception/CompanyNotFoundException.java
src/main/java/com/example/jobis/domain/user/domain/User.java
src/main/java/com/example/jobis/domain/user/domain/repository/UserRepository.java
src/main/java/com/example/jobis/domain/user/exception/UserNotFoundException.java
src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
src/main/java/com/example/jobis/global/exception/ExpiredTokenException.java
src/main/java/com/example/jobis/global/exception/InvalidTokenException.java
src/main/java/com/example/jobis/global/redis/RedisConfig.java
src/main/java/com/example/jobis/global/security/auth/AuthDetails.java
src/main/java/com/example/jobis/global/security/auth/AuthDetailsService.java
src/main/java/com/example/jobis/global/security/jwt/JwtFilter.java
src/main/java/com/example/jobis/global/security/jwt/JwtProperties.java
src/main/java/com/example/jobis/global/security/jwt/JwtTokenProvider.java

- close #9
- jwt auth refreshtoken

🔗 :: (#09) jwt auth

---

src/main/java/com/example/jobis/domain/company/domain/Attachment.java
src/main/java/com/example/jobis/domain/company/domain/Company.java
src/main/java/com/example/jobis/domain/company/domain/CompanyDetails.java
src/main/java/com/example/jobis/domain/recruit/domain/Recruit.java
src/main/java/com/example/jobis/domain/recruit/domain/RecruitArea.java
src/main/java/com/example/jobis/domain/recruit/domain/RequiredLicences.java
src/main/java/com/example/jobis/domain/recruit/domain/TechList.java
src/main/java/com/example/jobis/domain/recruit/domain/TechListId.java
src/main/java/com/example/jobis/domain/recruit/domain/enums/RecruitStatus.java
src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitAreaRepository.java
src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitRepository.java
src/main/java/com/example/jobis/domain/recruit/domain/repository/RequiredLicencesRepository.java
src/main/java/com/example/jobis/domain/recruit/domain/repository/TechListRepository.java
src/main/java/com/example/jobis/domain/recruit/domain/type/Pay.java
src/main/java/com/example/jobis/domain/recruit/domain/type/RecruitDate.java
src/main/java/com/example/jobis/domain/user/domain/User.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

- close #11 
- 모집의뢰 도메인작성
- 유저 엔티티에 매핑 안된거 몇개 추가
- 가독성 개선

🔗 :: (#11) 모집의뢰 도메인 작성

---

src/main/java/com/example/jobis/domain/user/controller/UserController.java
src/main/java/com/example/jobis/domain/user/controller/dto/response/TokenResponse.java
src/main/java/com/example/jobis/domain/user/service/LoginService.java
src/main/java/com/example/jobis/global/security/jwt/JwtFilter.java
src/main/java/com/example/jobis/global/security/jwt/JwtTokenProvider.java
src/main/resources/application.yml

- close #27
- 불필요 프린트 제거
- 로그인시 만료시간 response 추가

🔗 :: (#27)auth 로직 변경

---

src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java

⚙️ :: (#31) 회원가입 버그 수정

---

src/main/java/com/example/jobis/domain/user/controller/UserController.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

⚙️ :: (#30) 로그인 버그 수정

---

src/main/java/com/example/jobis/domain/code/domain/Code.java
src/main/java/com/example/jobis/domain/code/domain/enums/CodeType.java
src/main/java/com/example/jobis/domain/code/domain/repository/CodeRepository.java
src/main/java/com/example/jobis/domain/code/presentaion/CodeController.java
src/main/java/com/example/jobis/domain/code/presentaion/dto/response/CodeResponse.java
src/main/java/com/example/jobis/domain/code/service/FindCodeService.java
src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

- close #35 
- 코드테이블 추가
- 코드 조회 api
- 미사용 api삭제

🔗 :: (#35)코드 테이블

---

src/main/java/com/example/jobis/domain/student/domain/Portfolio.java
src/main/java/com/example/jobis/domain/student/domain/Student.java
src/main/java/com/example/jobis/domain/student/domain/types/Gender.java
src/main/java/com/example/jobis/domain/student/domain/types/Grade.java

- close #38 
- 학생, 포트폴리오 엔티티 추가
- 성별, 학년 enum 추가

🗂 :: (#38) 학생 엔티티 추가

---

src/main/java/com/example/jobis/domain/student/domain/Student.java
src/main/java/com/example/jobis/domain/teacher/domain/Teacher.java
src/main/java/com/example/jobis/domain/teacher/domain/repository/TeacherRepository.java

- close #34 
- 산학부 도메인 구조 및 엔티티 생성

🔗 :: (#34) 산학부(어드민) 도메인

---

src/main/java/com/example/jobis/domain/student/controller/StudentController.java
src/main/java/com/example/jobis/domain/student/controller/dto/request/StudentSignUpRequest.java
src/main/java/com/example/jobis/domain/student/service/StudentSignUpService.java
src/main/java/com/example/jobis/global/util/RegexProperty.java

🧩 :: (#48) 학생 회원가입 기능 추가

---

src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/service/ExistsCompanyService.java

- close #54 
- GET 요청에 RequestBody가 있는 버그 수정

⚙️ :: (#54) GET 요청에 RequestBody가 있는 버그 수정

---

src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/service/ExistsCompanyService.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

Revert "⚙️ :: (#54) GET 요청에 RequestBody가 있는 버그 수정"

---

src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/service/ExistsCompanyService.java

- close #57 
- GET 요청에 RequestBody가 있는 버그 수정

⚙️ :: (#57) GET 요청에 RequestBody가 있는 버그 수정

---

build.gradle
src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/service/ExistsCompanyService.java
src/main/java/com/example/jobis/domain/file/exception/FileNotFoundException.java
src/main/java/com/example/jobis/domain/file/exception/InvalidExtensionException.java
src/main/java/com/example/jobis/domain/file/presentation/FileController.java
src/main/java/com/example/jobis/domain/file/presentation/dto/response/FileUploadResponse.java
src/main/java/com/example/jobis/domain/file/presentation/type/FileType.java
src/main/java/com/example/jobis/domain/file/service/FileUploadService.java
src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java
src/main/java/com/example/jobis/infrastructure/s3/S3Properties.java
src/main/java/com/example/jobis/infrastructure/s3/S3Util.java
src/main/resources/application.yml

🔗 :: (#49)파일 업로드

---

src/main/java/com/example/jobis/infrastructure/s3/S3Util.java

- close #64 
- 파일 업로드시 유효한 확장자 검증 로직 변경
- 추후에 다시 바꿔야될거같기도함

🔗 :: (#64)파일 유효성 로직 변경

---

src/main/java/com/example/jobis/domain/code/controller/CodeController.java
src/main/java/com/example/jobis/domain/code/controller/dto/response/JobCodeResponse.java
src/main/java/com/example/jobis/domain/code/domain/Code.java
src/main/java/com/example/jobis/domain/code/domain/enums/JobType.java
src/main/java/com/example/jobis/domain/code/domain/repository/CodeRepository.java
src/main/java/com/example/jobis/domain/code/service/FindJobCodeService.java
src/main/java/com/example/jobis/domain/company/service/ExistsCompanyService.java
src/main/java/com/example/jobis/domain/student/service/SendSignUpAuthCodeService.java
src/main/java/com/example/jobis/domain/user/service/LoginService.java

- close #65 
- 직무코드 조회 api에 조회시 직무종류까지 보내주게
- 중간중간 빼먹은 `@Transactional`어노테이션 추가

🔗 :: (#65)직무코드 분류

---

src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/controller/dto/response/CompanyDetailsResponse.java
src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java
src/main/java/com/example/jobis/domain/company/service/QueryCompanyDetailsService.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

🧩 :: (#61) 회사 상세정보 조회 api

---

src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java

- close #79 
- try-catch로 exception 처리

⚙️ :: 존재하지 않는 사업자번호로 조회시 500 해결

---

src/main/java/com/example/jobis/domain/company/controller/dto/request/RegisterCompanyRequest.java

- close #76 
- 회사 회원가입 시 비밀번호 입력에 정규 표현식 수정
- 비밀번호는 숫자 4자리

🛩️ :: (#76) 회사 비밀번호 정규표현식 수정

---

src/main/java/com/example/jobis/domain/recruit/controller/dto/request/ApplyRecruitmentRequest.java
src/main/java/com/example/jobis/domain/recruit/domain/Recruit.java
src/main/java/com/example/jobis/domain/recruit/service/ApplyRecruitmentService.java

🔗 :: (#78)NPE해결

---

src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/com/example/jobis/domain/student/controller/StudentController.java
src/main/java/com/example/jobis/domain/student/service/StudentSignUpService.java
src/main/java/com/example/jobis/domain/user/controller/UserController.java
src/main/java/com/example/jobis/domain/user/controller/dto/response/UserAuthResponse.java
src/main/java/com/example/jobis/domain/user/domain/enums/Authority.java
src/main/java/com/example/jobis/domain/user/service/LoginService.java

- close #88
- 통합 로그인 Response DTO 추가
- 로그인시 계정 타입 반환 추가됨
- `Authority` emum에 `TEACHER`타입 추가됨

🔗 :: (#88) 로그인시 계정타입 반환

---

src/main/java/com/example/jobis/domain/file/presentation/FileController.java
src/main/java/com/example/jobis/domain/file/presentation/dto/request/DeleteFileRequest.java
src/main/java/com/example/jobis/domain/file/service/DeleteFileService.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java
src/main/java/com/example/jobis/infrastructure/s3/S3Util.java

- close #90 
- 파일 업로드시 풀경로 말고 파일 이름만 반환
- 파일 삭제

🔗 :: (#90)파일 삭제

---

src/main/java/com/example/jobis/domain/recruit/domain/Recruitment.java
src/main/java/com/example/jobis/domain/teacher/presentaion/TeacherController.java
src/main/java/com/example/jobis/domain/teacher/service/ChangeRecruitService.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

🔗:: (#95)모집의뢰 상태변경 기능추가

---

src/main/java/com/example/jobis/domain/code/domain/RecruitAreaCode.java
src/main/java/com/example/jobis/domain/company/controller/dto/request/RegisterCompanyRequest.java
src/main/java/com/example/jobis/domain/company/domain/Company.java
src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/com/example/jobis/domain/recruit/domain/enums/RecruitStatus.java
src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitmentRepository.java
src/main/java/com/example/jobis/domain/recruit/facade/RecruitFacade.java
src/main/java/com/example/jobis/domain/recruit/service/QueryRecruitListService.java
src/main/java/com/example/jobis/domain/student/controller/StudentController.java
src/main/java/com/example/jobis/domain/teacher/presentaion/TeacherController.java
src/main/java/com/example/jobis/domain/teacher/presentaion/dto/response/TQueryRecruitmentListResponse.java
src/main/java/com/example/jobis/domain/teacher/service/TeacherQueryRecruitmentListService.java
src/main/java/com/example/jobis/global/error/GlobalExceptionHandler.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java
src/main/java/com/example/jobis/infrastructure/s3/S3Util.java

- close #93 
- 모집의뢰 리스트를 조견별로 조회할 수 있게 함
- 학생 모집의뢰 조회에서 같은 메소드를 사용하게함
- 그외 리펙토링

🔗 :: (#93)선생님 모집의뢰 리스트 조회api

---

src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
src/main/java/com/example/jobis/domain/application/controller/dto/request/CreateApplicationRequest.java
src/main/java/com/example/jobis/domain/application/domain/Application.java
src/main/java/com/example/jobis/domain/application/domain/enums/ApplicationStatus.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationAttachmentJpaRepository.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/com/example/jobis/domain/application/exception/ApplicationAlreadyExistsException.java
src/main/java/com/example/jobis/domain/application/service/CreateApplicationService.java
src/main/java/com/example/jobis/domain/student/facade/StudentFacade.java
src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

- close #101 
- 기업 지원 api를 추가했어용

🧩 :: (#101) 기업 지원 api 추가

---

src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationListResponse.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/com/example/jobis/domain/application/service/QueryStudentApplicationService.java
src/main/java/com/example/jobis/domain/student/controller/StudentController.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

- close #106 
- 기업지원 내역 조회
- 접근권한 설정 오류 해결햇음 
- recruit -> recruitment로 엔드포인트 변경

🧩 :: (#106) 기업 지원 내역 api

---

src/main/java/com/example/jobis/domain/user/service/LoginService.java
src/test/java/com/example/jobis/domain/company/service/CompanyMyPageServiceTest.java
src/test/java/com/example/jobis/domain/company/service/RegisterCompanyServiceTest.java
src/test/java/com/example/jobis/domain/company/service/UpdateCompanyDetailsServiceTest.java
src/test/java/com/example/jobis/domain/teacher/service/ChangeRecruitmentStatusServiceTest.java
src/test/java/com/example/jobis/domain/user/service/LoginServiceTest.java

🔗 :: 누락된 테스트코드작성

---

src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationListResponse.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/com/example/jobis/domain/application/exception/InvalidStudentException.java
src/main/java/com/example/jobis/domain/application/service/DeleteApplicationService.java
src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
src/main/java/com/example/jobis/global/security/SecurityConfig.java

- close #116 
- 기업 지원 취소 api 추가

🧩 :: (#) 지원서 삭제 api 추가

---

src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
src/main/java/com/example/jobis/domain/application/domain/Application.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/com/example/jobis/domain/application/service/CreateApplicationService.java
src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitmentRepository.java

- close #120 
- 기업지원 엔티티 조인 company -> recruitment로 변경

🛠️ :: (#120) 지원서 리팩토링

---

.github/CODEOWNERS

🔗 :: codeowners

---

src/main/java/team/returm/jobis/JobisApplication.java
src/main/java/team/returm/jobis/domain/company/domain/type/Manager.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/vo/QueryRecruitmentsVO.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
src/main/java/team/returm/jobis/domain/recruitment/service/ChangeRecruitmentStatusSchedulerService.java
src/main/java/team/returm/jobis/domain/recruitment/service/TeacherChangeRecruitmentStatusService.java
src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
src/main/java/team/returm/jobis/global/scheduler/RecruitmentScheduler.java

- close #114
- 프로젝트에 스케줄링 기능 추가
- 모집의뢰 상태변경 스케줄러 서비스 추가

🔗 :: 모집의뢰 상태변경 스케줄러

---

src/main/java/team/returm/jobis/domain/company/domain/Company.java
src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/team/returm/jobis/domain/recruitment/domain/Recruitment.java
src/main/java/team/returm/jobis/domain/student/domain/Student.java
src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
src/main/java/team/returm/jobis/domain/teacher/domain/Teacher.java
src/main/resources/application.yml

- user와 oneToone관계인 엔티티들에 PERSIST전이를 하여 각 엔티티를 영속화시 user가 함께 영속화도록 변경
- Recruitment, RegisterCompanyService
close #145

🔗 :: (#145) cascade 적용

---

src/main/java/team/returm/jobis/domain/code/domain/RecruitAreaCode.java
src/main/java/team/returm/jobis/domain/recruitment/domain/Recruitment.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/exception/RecruitmentCannotDeleteException.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
src/main/java/team/returm/jobis/domain/recruitment/service/CreateRecruitAreaService.java
src/main/java/team/returm/jobis/domain/recruitment/service/DeleteRecruitmentService.java
src/main/java/team/returm/jobis/domain/recruitment/service/RemoveRecruitmentService.java
src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitAreaService.java
src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitmentService.java
src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- DELETE /recruitments/{recruitmet-id}
- 모집의뢰 삭제 api
- RemoveRecruitmentService
close #152

🔗 :: 모집의뢰 삭제 api

---

src/main/java/team/returm/jobis/domain/code/domain/repository/CodeJpaRepository.java
src/main/java/team/returm/jobis/domain/code/service/QueryTechCodesService.java

- 기존의 기술코드 조회시 타입무관하게 모두 조회되던 버그 수정
- QueryTechCodesService
close #148

🔗 :: (#148) codeType조건 추가

---

build.gradle
src/main/java/team/returm/jobis/domain/auth/domain/AuthCode.java
src/main/java/team/returm/jobis/domain/auth/exception/AuthCodeNotFoundException.java
src/main/java/team/returm/jobis/domain/auth/facade/AuthCodeFacade.java
src/main/java/team/returm/jobis/domain/auth/presentation/dto/request/SendAuthCodeRequest.java
src/main/java/team/returm/jobis/domain/auth/service/SendAuthCodeService.java
src/main/java/team/returm/jobis/domain/auth/service/VerifyAuthCodeService.java
src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
src/main/java/team/returm/jobis/domain/student/service/UpdateStudentPasswordService.java
src/main/java/team/returm/jobis/domain/user/domain/repository/UserRepository.java
src/main/java/team/returm/jobis/domain/user/facade/UserFacade.java
src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
src/main/java/team/returm/jobis/global/util/StringUtil.java
src/main/java/team/returm/jobis/global/util/jms/JmsUtil.java
src/main/resources/templates/signup-template.html

- 이메일 템플릿 설정
- 코드 개편
- SendAuthCodeService
close #162

🔗 :: (#162)이메일 템플릿 설정

---

src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentJpaRepository.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/request/ChangeRecruitmentRequest.java
src/main/java/team/returm/jobis/domain/recruitment/service/TeacherChangeRecruitmentStatusService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 모집의뢰 변경 api에서 모집의뢰를 다중 선택할 수 있게 변경
- TeacherChangeRecruitmentStatusService
close #166

🔗 :: (#166) 모집의뢰 상태 다중변경

---

src/main/java/team/returm/jobis/domain/company/domain/Company.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java

- 회사소개 컬럼 수 증가
- Company
close #170

🔗 :: (#170) 컬럼 수 증가

---

src/main/java/team/returm/jobis/domain/company/domain/Company.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java

- 회사 entity에 사업자등록증을 받는 칼럼 추가
- Company
- RegisterCompanyService
close #173

🔗 :: (#173) 사업자등록증 칼럼 추가

---

src/main/java/team/returm/jobis/domain/student/domain/Student.java
src/main/java/team/returm/jobis/domain/student/presentation/dto/request/StudentSignUpRequest.java
src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java

- 전화번호 컬럼제거
- Student
close #181

🔗 :: (#181) 전화번호 컬럼 제거

---

src/main/java/team/returm/jobis/domain/auth/presentation/AuthController.java
src/main/java/team/returm/jobis/domain/auth/service/TokenReissueService.java
src/main/java/team/returm/jobis/domain/user/presentation/UserController.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- reissue api의 endpoint변경
- AuthController
close #184

🔗 :: (#184) 토큰 재발급 api위치 변경

---

src/main/java/team/returm/jobis/domain/company/domain/Company.java
src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyJpaRepository.java
src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/request/UpdateCompanyTypeRequest.java
src/main/java/team/returm/jobis/domain/company/service/UpdateCompanyTypeService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 기업 구분 변경 api 추가
- UpdateCompanyTypeService
close #180

🔗 :: (#180) 기업구분 변경 api

---

src/main/java/team/returm/jobis/domain/acceptance/domain/Acceptance.java
src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceJpaRepository.java
src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java

- 합격자 엔티티 생성
- Acceptance
close #193

🔗 :: (#193) Acceptance 엔티티 생성

---

src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java

- 모집 시작일, 종료일 비교 부분 수정
- RecruitmentRepository
close #198

🔗 :: (#198) 선생님 모집의뢰 리스트 조회 수정

---

src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/application/presentation/ApplicationController.java
src/main/java/team/returm/jobis/domain/application/presentation/dto/request/QueryApplicationsRequest.java
src/main/java/team/returm/jobis/domain/application/service/QueryCompanyApplicationsService.java
src/main/java/team/returm/jobis/domain/application/service/QueryStudentApplicationsService.java
src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java

- 선생님 지원자 조회시 company_id query string 추가
- TeacherQueryApplicationsService
close #203

🔗 :: (#203) 지원서 조회시 company_id querystring 추가

---

src/main/java/team/returm/jobis/domain/acceptance/domain/Acceptance.java
src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceJpaRepository.java
src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java
src/main/java/team/returm/jobis/domain/acceptance/presentation/AcceptanceController.java
src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
src/main/java/team/returm/jobis/domain/acceptance/service/TeacherQueryFieldTraineesAndContractWorkersService.java
src/main/java/team/returm/jobis/domain/application/domain/Application.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/application/domain/repository/vo/QueryFieldTraineesVO.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 현장실습생, 근로계약생 조회 api
- TeacherQueryFieldTraineesAndContractWorkersService
close #202

🔗 :: (#202) 현장실습생, 근로계약생 조회 api

---

src/main/java/team/returm/jobis/domain/code/domain/Code.java
src/main/java/team/returm/jobis/domain/code/domain/enums/CodeType.java
src/main/java/team/returm/jobis/domain/code/presentation/CodeController.java
src/main/java/team/returm/jobis/domain/code/service/QueryBusinessAreaCodesService.java
src/main/java/team/returm/jobis/domain/code/service/QueryTechCodesService.java
src/main/java/team/returm/jobis/domain/company/domain/Company.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java
src/main/java/team/returm/jobis/global/util/StringUtil.java

- 사업분야, 서비스명 칼럼 추가
- 사업분야 코드타입 추가
- 사업분야 코드 조회 api 추가
- CodeType
- Company
- QueryBusinessAreaCodesService
close #179

🔗 :: (#179) 사업분야, 서비스명 칼럼 추가

---

src/main/java/team/returm/jobis/domain/acceptance/domain/Acceptance.java
src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java
src/main/java/team/returm/jobis/domain/acceptance/domain/repository/vo/ApplicationDetailVO.java
src/main/java/team/returm/jobis/domain/acceptance/presentation/AcceptanceController.java
src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/request/RegisterEmploymentContractRequest.java
src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
src/main/java/team/returm/jobis/domain/acceptance/service/RegisterEmploymentContractService.java
src/main/java/team/returm/jobis/domain/acceptance/service/TeacherQueryFieldTraineesAndContractWorkersService.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/application/domain/repository/vo/QueryFieldTraineesVO.java
src/main/java/team/returm/jobis/domain/application/service/ChangeApplicationsStatusService.java
src/main/java/team/returm/jobis/domain/recruitment/service/ApplyRecruitmentService.java
src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitmentService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java
src/main/java/team/returm/jobis/global/util/StringUtil.java

- POST /acceptences/employment
- RegisterEmploymentContractService
- 근로계약 전환 로직 추가
- 현장실습생리슽 조회 api에서 근로계약 전환시 필요한 application_id필드 추가
close #210

🔗 :: (#210) 근로계약 전환 api

---

src/main/java/team/returm/jobis/domain/acceptance/domain/Acceptance.java
src/main/java/team/returm/jobis/domain/review/domain/Review.java
src/main/java/team/returm/jobis/domain/review/domain/enums/ReviewType.java
src/main/java/team/returm/jobis/domain/review/domain/repository/ReviewJpaRepository.java
src/main/java/team/returm/jobis/domain/review/domain/repository/ReviewRepository.java

- Review 도메인 세팅
- Review Entity
- Review Repository
close #220

🔗 :: (#220) 면접 후기 테이블 추가

---

src/main/java/team/returm/jobis/domain/bookmark/domain/BookMarkId.java
src/main/java/team/returm/jobis/domain/bookmark/domain/Bookmark.java
src/main/java/team/returm/jobis/domain/bookmark/domain/repository/BookmarkJpaRepository.java
src/main/java/team/returm/jobis/domain/bookmark/domain/repository/BookmarkRepository.java
src/main/java/team/returm/jobis/domain/student/domain/Student.java

- 북마크 테이블 생성
- Bookmark
close #221

🔗 :: (#221) 북마크 테이블 생성

---

src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
src/main/java/team/returm/jobis/domain/company/domain/repository/vo/TeacherQueryCompaniesVO.java
src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/response/TeacherQueryCompaniesResponse.java
src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java
src/main/java/team/returm/jobis/global/util/StringUtil.java

- 선생님이 등록페이지에서 사용할 회사 조회 api
- TeacherQueryCompaniesService
close #228

🔗 :: (#228) 선생님 회사 조회 api

---

src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentJpaRepository.java
src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentRepository.java
src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
src/main/java/team/returm/jobis/domain/student/service/VerifyStudentService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 학생인증 api추가
- 
- VerifiStudentService
close #235

🔗 :: (#235) 학생인증 api

---

src/main/java/team/returm/jobis/domain/file/presentation/FileController.java

- 파일 삭제시 body대신 querystring으로 변경
- FileController
close #239

🔗 :: (#239) 파일 삭제 요청 객체 변경

---

src/main/java/team/returm/jobis/domain/bookmark/domain/Bookmark.java
src/main/java/team/returm/jobis/domain/bookmark/domain/BookmarkId.java
src/main/java/team/returm/jobis/domain/bookmark/domain/repository/BookmarkJpaRepository.java
src/main/java/team/returm/jobis/domain/bookmark/domain/repository/BookmarkRepository.java
src/main/java/team/returm/jobis/domain/bookmark/domain/repository/vo/QueryStudentBookmarksVO.java
src/main/java/team/returm/jobis/domain/bookmark/exception/BookmarkNotFoundException.java
src/main/java/team/returm/jobis/domain/bookmark/presentation/BookmarkController.java
src/main/java/team/returm/jobis/domain/bookmark/presentation/dto/response/QueryStudentBookmarksResponse.java
src/main/java/team/returm/jobis/domain/bookmark/service/CreateBookmarkService.java
src/main/java/team/returm/jobis/domain/bookmark/service/DeleteBookmarkService.java
src/main/java/team/returm/jobis/domain/bookmark/service/QueryStudentBookmarksService.java
src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 북마크 관련 api를 만들엇어용
- CreateBookmarkService
- DeleteBookmarkService
- QueryStudentBookmarksService
close #237

🔗 :: (#237) 북마크 관련 api

---

src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentJpaRepository.java
src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentRepository.java
src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
src/main/java/team/returm/jobis/domain/student/service/VerifyStudentService.java

- 학생 존재 여부 인증 회원가입시 정보 삭제하게 변경
- StudentSignUpService
- VerifyStudentService
close #247

🔗 :: (#247) 학생 존재 여부 인증 회원가입시 정보 삭제하게 변경

---

src/main/resources/templates/signup-template.html

- 템플릿 연락처 정보 변경
- 
- 
close #251

🔗 :: (#251) 이메일 템플릿 수정

---

src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java

- 모집의뢰서 지원자 수 버그 해결
- recruitmentRepository
close #259

🔗 :: (#259) 선생님 모집의뢰서 조회 버그

---

src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/QueryRecruitmentDetailResponse.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/RecruitAreaResponse.java
src/main/java/team/returm/jobis/domain/recruitment/service/QueryRecruitmentDetailService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 선생님 모집의뢰 상세조회
- 기존에 StudentQueryRecruitDetailService와 response가 같기 때문에 재사용
close #268

🔗 :: (#268) 선생님 모집의뢰 상세 조회

---

src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/application/presentation/dto/response/TeacherQueryApplicationsResponse.java
src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/domain/type/RecruitDate.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/RecruitmentFilter.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/TeacherQueryRecruitmentsResponse.java
src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentsService.java
src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java

- 페이지 총 개수 반환
- 페이지개수용 쿼리 추가
- 모집의뢰 필터객체 추가
close #225

🔗 :: (#225) 페이지 총 개수 반환

---

src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
src/main/java/team/returm/jobis/domain/code/presentation/CodeController.java
src/main/java/team/returm/jobis/domain/code/presentation/dto/response/CodesResponse.java
src/main/java/team/returm/jobis/domain/code/service/QueryCodesService.java
src/main/java/team/returm/jobis/global/util/StringUtil.java

- parent code로 조회 필터 추가
- QueryCodesService
close #272

🔗 :: (#272) parent code로 조회 필터 추가

---

src/main/java/team/returm/jobis/domain/company/domain/Company.java
src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
src/main/java/team/returm/jobis/domain/company/domain/repository/vo/QueryCompanyDetailsVO.java
src/main/java/team/returm/jobis/domain/company/domain/repository/vo/StudentQueryCompaniesVO.java
src/main/java/team/returm/jobis/domain/company/domain/repository/vo/TeacherQueryCompaniesVO.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsRequest.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/response/CompanyMyPageResponse.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/response/QueryCompanyDetailsResponse.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/response/TeacherQueryCompaniesResponse.java
src/main/java/team/returm/jobis/domain/company/service/CompanyMyPageService.java
src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
src/main/java/team/returm/jobis/domain/student/domain/Student.java
src/main/java/team/returm/jobis/domain/student/presentation/dto/request/StudentSignUpRequest.java
src/main/java/team/returm/jobis/domain/student/presentation/dto/response/StudentMyPageResponse.java
src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
src/main/java/team/returm/jobis/global/util/ImageProperty.java

- 학생 프로필 이미지 추가
- 매출액 이름 통일
- Student
close #276

🔗 :: (#276) 프로필 이미지 추가

---

src/main/java/team/returm/jobis/domain/application/exception/error/ApplicationErrorCode.java
src/main/java/team/returm/jobis/domain/auth/exception/error/AuthErrorCode.java
src/main/java/team/returm/jobis/domain/bookmark/exception/error/BookmarkErrorCode.java
src/main/java/team/returm/jobis/domain/code/exception/error/CodeErrorCode.java
src/main/java/team/returm/jobis/domain/company/exception/error/CompanyErrorCode.java
src/main/java/team/returm/jobis/domain/file/exception/error/FileErrorCode.java
src/main/java/team/returm/jobis/domain/recruitment/exception/error/RecruitmentErrorCode.java
src/main/java/team/returm/jobis/domain/review/exception/error/ReviewErrorCode.java
src/main/java/team/returm/jobis/domain/student/exception/error/StudentErrorCode.java
src/main/java/team/returm/jobis/domain/teacher/exception/error/TeacherErrorCode.java
src/main/java/team/returm/jobis/domain/user/exception/error/UserErrorCode.java
src/main/java/team/returm/jobis/global/error/ErrorProperty.java
src/main/java/team/returm/jobis/global/error/GlobalExceptionFilter.java
src/main/java/team/returm/jobis/global/error/GlobalExceptionHandler.java
src/main/java/team/returm/jobis/global/error/exception/GlobalErrorCode.java

- status를 숫자에서 HttpStatus이넘으로 변경
- %ErrorCode
close #270

🔗 :: (#270) status를 숫자에서 HttpStatus이넘으로 변경

---

src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
src/main/java/team/returm/jobis/domain/bookmark/service/BookmarkService.java
src/main/java/team/returm/jobis/domain/code/presentation/dto/response/CodesResponse.java
src/main/java/team/returm/jobis/domain/code/service/QueryCodesService.java
src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
src/main/java/team/returm/jobis/domain/recruitment/domain/type/RecruitDate.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
src/main/java/team/returm/jobis/domain/review/domain/Review.java
src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
src/main/java/team/returm/jobis/domain/student/service/StudentMyPageService.java
src/main/java/team/returm/jobis/global/error/ErrorProperty.java
src/main/java/team/returm/jobis/global/exception/ExpiredTokenException.java

🔗 :: (#283) lint

---

src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentRequest.java
src/main/java/team/returm/jobis/global/annotation/ValidListElements.java

- 비었거나 요소가 Null List를 검증하는 커스텀 어노테이션 추가
- @ValidListElements
close #290

🔗 :: (#290) 리스트 요소 검증 어노테이션 추가

---

src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
src/main/java/team/returm/jobis/domain/company/domain/repository/vo/TeacherQueryCompaniesVO.java
src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/CompanyFilter.java
src/main/java/team/returm/jobis/domain/company/presentation/dto/response/TeacherQueryCompaniesResponse.java
src/main/java/team/returm/jobis/domain/company/service/StudentQueryCompaniesService.java
src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java

- 총 페이지 개수 반환
- 합격자수 서브쿼리로 변경
- 페이지 개수 반환
close #287

🔗 :: (#287) 기업조회 총 페이지 개수 반환

---

src/main/java/team/returm/jobis/domain/file/exception/FileUploadFailedException.java
src/main/java/team/returm/jobis/domain/file/exception/error/FileErrorCode.java
src/main/java/team/returm/jobis/domain/file/presentation/FileController.java
src/main/java/team/returm/jobis/domain/file/presentation/dto/response/FileUploadResponse.java
src/main/java/team/returm/jobis/domain/file/service/FileUploadService.java
src/main/java/team/returm/jobis/global/config/AsyncConfig.java
src/main/java/team/returm/jobis/infrastructure/s3/S3Util.java
src/main/resources/application.yml

- 파일 다중 업로드 구현
-
- 파일이 여려개가 됨으로 인해 반환시간이 많이 길어지기 때문에 비동기 처리 추가
close #292

🔗 :: (#292) 파일 다중 업로드

---

src/main/java/team/returm/jobis/domain/application/domain/Application.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/review/domain/Review.java
src/main/java/team/returm/jobis/domain/review/presentation/dto/QueryReviewDetailResponse.java
src/main/java/team/returm/jobis/domain/review/presentation/dto/QueryReviewsResponse.java
src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
src/main/java/team/returm/jobis/domain/review/service/QueryReviewDetailService.java
src/main/java/team/returm/jobis/domain/review/service/QueryReviewsService.java

- review 반환 시 createdDate 필드 제거
- review 반환 시 createdDate 필드 제거
- applicationStatus가 REQUESTED, APPROVED, REJECTED이면 review 작성 못하도록 변경
close #285

🔗 :: (#285) review created_date 제거

---

src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/QueryRecruitmentDetailResponse.java
src/main/java/team/returm/jobis/domain/recruitment/service/QueryRecruitmentDetailService.java

- 모집의뢰서 상세조회시 회사 사진 반환
- QueryRecruitmentDetailService
close #289

🔗 :: (#289) 모집의뢰서 상세조회시 회사 사진 반환

---

src/main/java/team/returm/jobis/domain/file/service/FileUploadService.java
src/main/java/team/returm/jobis/infrastructure/s3/S3Properties.java

- 파일 업로드 반환시 s3 url 같이 반환
- FileUploadService
close #297

🔗 :: (#297) 파일 업로드 반환시 s3 url 같이 반환

---

src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
src/main/java/team/returm/jobis/global/util/StringUtil.java

- code=wqw code=wq code=sds 에서 code=dsd,wqewq,wqwq로
- RecruitmentController
close #309

🔗 :: (#309) 콤마 리스트 구분

---

src/main/java/team/returm/jobis/domain/acceptance/service/CancelFieldTraineesService.java
src/main/java/team/returm/jobis/domain/acceptance/service/ChangeContractDateService.java
src/main/java/team/returm/jobis/domain/application/domain/Application.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/application/service/ChangeFieldTrainDateService.java
src/main/java/team/returm/jobis/domain/application/service/CreateApplicationService.java
src/main/java/team/returm/jobis/domain/application/service/DeleteApplicationService.java
src/main/java/team/returm/jobis/domain/auth/domain/AuthCode.java
src/main/java/team/returm/jobis/domain/auth/service/VerifyAuthCodeService.java
src/main/java/team/returm/jobis/domain/student/domain/Student.java

- 도메인 모델에 로직을 담아 코드 응집도 ⬆️ 
- 
close #312

🔗 :: (#312) 리펙토링

---

src/main/java/team/returm/jobis/domain/student/domain/Student.java
src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
src/main/java/team/returm/jobis/domain/student/presentation/dto/request/UpdateStudentProfileRequest.java
src/main/java/team/returm/jobis/domain/student/service/UpdateStudentProfileService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 학생 프로필 변경 api
-
- 
- 
close #316

🔗 :: (#316) 학생 프로필사진 변경 api

---

src/main/java/team/returm/jobis/domain/recruitment/domain/RecruitArea.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/vo/RecruitAreaVO.java
src/main/java/team/returm/jobis/domain/recruitment/facade/RecruitmentFacade.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/RecruitmentFilter.java
src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentsService.java

- 학생 모집의뢰 리스트 조회 jobcode 필터 추가 
- StudentQueryRecruitmentsService
close #319

🔗 :: (#319) 학생 모집의뢰 리스트 조회 jobcode 필터 추가 

---

src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/service/ChangeRecruitmentStatusSchedulerService.java

- 승인된 모집의뢰서만 스케줄링
-
- ChangeRecruitmentStatusSchedulerService
close #330

🔗 :: (#330) 승인된 모집의뢰서만 스케줄링

---

src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/returm/jobis/domain/application/service/CreateApplicationService.java

- APPROVED, FIELD_TRAIN, PASS는 지원 요청 불가
- 
- 
close #336

🔗  :: (#336) APPROVED, FIELD_TRAIN, PASS는 지원 요청 불가

---

src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentJpaRepository.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/exception/RecruitmentAlreadyExistsException.java
src/main/java/team/returm/jobis/domain/recruitment/exception/error/RecruitmentErrorCode.java
src/main/java/team/returm/jobis/domain/recruitment/service/ApplyRecruitmentService.java

- 모집의뢰서가 진행중일때 다른 모집의뢰서를 생성하지 못하게 함
- ApplyRecruitmentService
close #332

🔗 :: (#332) 모집의뢰서가 진행중일때 다른 모집의뢰서를 생성하지 못하게 함

---

src/main/java/team/returm/jobis/domain/application/service/QueryCompanyApplicationsService.java
src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
src/main/java/team/returm/jobis/domain/recruitment/service/QueryMyRecruitmentService.java
src/main/java/team/returm/jobis/domain/user/presentation/UserController.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- String businessAreaKeyword = codeFacade.findCodeById(businessArea).getKeyword();
- businessArea이게 널이라서 java.lang.IllegalArgumentException 발생
- QueryMyRecruitmentService NotFound 안터져서 500
- TeacherQueryCompaniesService
- QueryCompanyApplicationsService
- QueryMyRecruitmentService
close #340

🔗 :: (#340) 500 에러 해결

---

src/main/java/team/returm/jobis/domain/bug/domain/BugAttachment.java
src/main/java/team/returm/jobis/domain/bug/domain/BugAttachmentId.java
src/main/java/team/returm/jobis/domain/bug/domain/BugReport.java
src/main/java/team/returm/jobis/domain/bug/domain/enums/DevelopmentArea.java
src/main/java/team/returm/jobis/domain/code/domain/Code.java

- 버그 엔티ㅣㅌ
- BugReport
- BugAttachment
close #324

🔗 :: (#324) 버그 엔티티 생성

---

src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
src/main/java/team/returm/jobis/domain/student/presentation/dto/request/UpdateForgottenPasswordRequest.java
src/main/java/team/returm/jobis/domain/student/presentation/dto/request/UpdatePasswordRequest.java
src/main/java/team/returm/jobis/domain/student/service/CheckStudentPasswordService.java
src/main/java/team/returm/jobis/domain/student/service/UpdateStudentForgottenPasswordService.java
src/main/java/team/returm/jobis/domain/student/service/UpdateStudentPasswordService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

-  비밀번호 변경 api
- 비밀번호 체크 api
- 
- 
close #344

🔗 :: (#344) 비밀번호 변경 

---

src/main/java/team/returm/jobis/domain/user/domain/enums/Authority.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java
src/main/java/team/returm/jobis/global/security/jwt/JwtTokenProvider.java

- 우리 권한
- Authority
close #318

🔗 :: (#318) 개발자 권한 추가

---

src/main/java/team/returm/jobis/domain/bug/domain/repository/BugAttachmentRepository.java
src/main/java/team/returm/jobis/domain/bug/domain/repository/BugReportJpaRepository.java
src/main/java/team/returm/jobis/domain/bug/domain/repository/BugRepository.java
src/main/java/team/returm/jobis/domain/bug/presentation/BugController.java
src/main/java/team/returm/jobis/domain/bug/presentation/dto/request/CreateBugReportRequest.java
src/main/java/team/returm/jobis/domain/bug/service/CreateBugReportService.java
src/main/java/team/returm/jobis/global/security/SecurityConfig.java

- 버그 제보 api
- CreateBugReportService
close #346

🔗 :: (#346) 버그 제보 api

---

src/main/java/team/retum/jobis/domain/application/service/CreateApplicationService.java
src/main/java/team/retum/jobis/domain/recruitment/domain/Recruitment.java
src/main/java/team/retum/jobis/domain/recruitment/exception/InvalidRecruitmentStatusException.java
src/main/java/team/retum/jobis/domain/recruitment/exception/error/RecruitmentErrorCode.java

- 지원요청 시 모집의뢰가 모집중인 것만 가능하게
- Recruitment
close #353

⚒️ :: (#353) 지원요청 가능여부 도메인 로직추가

---

src/main/java/team/retum/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/retum/jobis/domain/application/domain/repository/vo/QueryApplicationVO.java
src/main/java/team/retum/jobis/domain/application/presentation/dto/response/CompanyQueryApplicationsResponse.java
src/main/java/team/retum/jobis/domain/application/service/QueryCompanyApplicationsService.java

- 기업 지원자 조회 할 때 지원자 프로필 추가 
- 
- 
close #355

🔗 :: (#355) 기업 지원자 조회 할 때 지원자 프로필 추가 

---

src/main/java/team/retum/jobis/domain/application/domain/ApplicationAttachment.java
src/main/java/team/retum/jobis/domain/application/domain/enums/AttachmentType.java
src/main/java/team/retum/jobis/domain/application/domain/repository/ApplicationRepository.java
src/main/java/team/retum/jobis/domain/application/domain/repository/vo/QueryApplicationVO.java
src/main/java/team/retum/jobis/domain/application/presentation/dto/request/CreateApplicationRequest.java
src/main/java/team/retum/jobis/domain/application/presentation/dto/response/AttachmentResponse.java
src/main/java/team/retum/jobis/domain/application/presentation/dto/response/CompanyQueryApplicationsResponse.java
src/main/java/team/retum/jobis/domain/application/presentation/dto/response/StudentQueryApplicationsResponse.java
src/main/java/team/retum/jobis/domain/application/presentation/dto/response/TeacherQueryApplicationsResponse.java
src/main/java/team/retum/jobis/domain/application/service/ChangeFieldTrainDateService.java
src/main/java/team/retum/jobis/domain/application/service/CreateApplicationService.java
src/main/java/team/retum/jobis/domain/application/service/QueryCompanyApplicationsService.java
src/main/java/team/retum/jobis/domain/application/service/QueryStudentApplicationsService.java
src/main/java/team/retum/jobis/domain/application/service/TeacherQueryApplicationsService.java
src/main/java/team/retum/jobis/domain/bug/domain/BugReport.java
src/main/java/team/retum/jobis/domain/bug/presentation/dto/request/CreateBugReportRequest.java
src/main/java/team/retum/jobis/domain/company/service/RegisterCompanyService.java
src/main/java/team/retum/jobis/domain/file/service/FileUploadService.java
src/main/java/team/retum/jobis/domain/recruitment/domain/Recruitment.java
src/main/java/team/retum/jobis/domain/student/domain/Student.java
src/main/java/team/retum/jobis/domain/student/presentation/StudentController.java

🔗 :: (334) 지원서 파일 구분

---

src/main/java/team/retum/jobis/global/web/WebSecurityConfig.java

- CSRF방지용설정
-
- WebSecurityConfig
close #358

🔗 :: (#358) CORS 설정

---

src/main/java/team/retum/jobis/domain/bug/domain/repository/BugReportRepository.java

- 개발 분야가 ALL일 때 전체 다 불러오도록 수정
- BugReportRepository
close #363

🔗 :: (#363) 개발 분야가 ALL일 때 전체 다 불러오도록 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/entity/StudentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/StudentMapper.java

🔗 :: (#366) toEntity함수 버그 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/StudentMapper.java

- 내 모집의뢰서 조회 api에서 모집의뢰 id반환
-
- 
- 
close #374

🔗 :: (#374) 기업 내 모집의뢰서 조회 id반환

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryReviewAvailableCompaniesResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryReviewAvailableCompaniesUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryReviewAvailableCompanyVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- GET /companies/review
- QueryReviewAvailableCompaniesUseCase
- api 개발
close #376

🔗 :: (#376) 후기 작성 가능기업조회 api

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java

- 기업저장 버그 수정
-
- 
- 
close #378

🔗 :: (#378) 기업저장 버그 수정

---

jobis-infrastructure/build.gradle
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FirebaseConfig.java
jobis-infrastructure/src/main/resources/application.yml

- 알림기능 구현을 위한 파이어베이스를 연동함
- FirebaseConfig
close #380

🔗 :: (#380) firebase 세팅

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateMouUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitmentUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java

- 모집의뢰서 수정이 안되던 버그 해결
- UpdateRecruitmentUseCase
close #383

🔗 :: (#383) 모집의뢰서 수정이 안되던 버그

---

jobis-application/src/main/java/team/retum/jobis/common/annotation/Service.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CreateRecruitAreaUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/annotation/config/ComponentScanConfig.java

- 겹치는부분 service로 분리
-
- 
- 
close #385

🔗 :: (#385) 모집분야관련 리펙토링

---

jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/review/dto/CreateReviewRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryReviewPort.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/dto/CreateReviewWebRequest.java

🔗 :: (#382) 후기 작성 applicationId 제거

---

jobis-application/src/main/java/team/retum/jobis/common/spi/SecurityPort.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/RegisterFieldTraineeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/DeleteApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryCompanyApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryStudentApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/bookmark/usecase/BookmarkUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CompanyMyPageUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/CheckStudentPasswordUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentMyPageUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentPasswordUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentProfileUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/LoginUseCase.java
jobis-infrastructure/build.gradle
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/teacher/persistence/entity/TeacherEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/teacher/persistence/mapper/TeacherMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/aop/ThreadLocalAspect.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/CurrentUserHolder.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/ThreadLocalService.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetailsService.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetailsService.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetailsService.java

- 인증할때 저장하는 객체 thread local에 저장 및 재사용
-
- SecurityPort
- 
close #389

🔗 :: (#389) ThreadLocal적용

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/entity/UserEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/mapper/UserMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/config/MysqlDialectConfig.java

- group_concat시 distinct추가
-
- MysqlDialect Config
close #394

🔗 :: (#394) 모집의뢰 조회 버그

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java

- 프론트엔드의 요청으로 기업 정보에서 수정가능한 칼럼을 추가했어용
- UpdateCompanyDetailsUseCase
close #399

🔗 :: (#399) 기업수정 칼럼 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CompanyMyPageUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#401) 기업 정보 수정할 때 식별키 받아와 수정  

---

jobis-infrastructure/build.gradle
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
jobis-infrastructure/src/main/resources/application.yml

- 이하성이 만든 Actuator 가 닫혀있어요
- 제가 브랜치를 지웠었네요,, 왜지
- 
- 
close #396

🔗 :: (#396) Actuator설정

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CheckCompanyExistsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/api/FeignClientAdapter.java

- 존재하지 않는 사업자번호 입력시 CompanyNotExistsException
- CheckCompanyExistsUseCase
close #411

🔗 :: (#411) 존재하지 않는 사업자번호 입력시 CompanyNotExistsException

---

jobis-application/src/main/java/team/retum/jobis/domain/bug/model/BugReport.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/PublishBugReportEventPort.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/CreateBugReportUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/BugReportHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/BugReportPublisher.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/PublishBugReportEventAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/model/BugReportEvent.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/WebhookUtil.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/slack/SlackAdapter.java

- 버그 첨부자료의 존재 여부에 따라 로직을 분리
- 코드 리팩토링
- 
- 
close #406

🔗 :: (#406) 이미지가 없을 때 슬랙 버그 내용이 안뜨는 문제 해결

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/StudentQueryCompaniesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java

- 클라 요구로 limit 12로 변경
- 
- 
close #417

🧩 :: (#417) 학생 모집의뢰서, 기업 리스트 조회 limit 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationAttachment.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java

🔗 :: (#419) 같은 모집의뢰 동시지원 방지

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/TeacherQueryApplicationsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/TeacherQueryEmployCompaniesResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/StudentQueryCompaniesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryEmployCompaniesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#430) 페이징 분리

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java

- 총인원 3학년만 숫자 세게 변경
- 
- 
close #432

🔗 :: (#432) 취업 명수 버그

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- page에 음수 들어오면 예외 발생
-
- page param valiation추가
- 
close #436

🔗 :: (#436) page에 음수 들어오는 문제

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/dto/request/ChangeApplicationsStatusWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentsVO.java

- fetch join 문제
- 
- 
close #445

🔗 :: (#445) fetch join으로 인한 in query 문제

---

jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java

- 코드 사용여부를 추가했스빈다.
- Code
close #444

🔗 :: (#444) 코드 사용여부 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java

Reverts Team-return/JOBIS-DSM-BE#447

Revert "🔗 :: (#444) 코드 사용여부 추가"

---

jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java

- develop 브랜치에 다시 머지합니다
- 
- 
close #

🔗 :: (#444) 코드사용여부추가

---

jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
jobis-application/src/main/java/team/retum/jobis/domain/code/service/GetKeywordsService.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitAreaResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/GetRecruitmentDetailService.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java

- 코드 이름이 아니라 코드 id 뜸
- 
- 
close #449

🔗 :: (#449) 내 모집의뢰 조회 시 jobcode가 제대로 안뜸

---

jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-application/src/main/java/team/retum/jobis/domain/student/model/Student.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java

- 모집의뢰 등록 시 동계인턴 용 모집의뢰인지 구분하기 위한 컬럼 추가
- Recruitment
close #455

🔗 :: (#455) 동계인턴 구분 칼럼 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/UpdateForgottenPasswordWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/UpdatePasswordWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/dto/request/LoginWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

- 비밀번호 유효성 검사 통일
- 
- 
close #461

🔗 :: (#461) 기업 비밀번호 설정 변경 기능 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/RecruitmentFilter.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java

- 모집의뢰서 등록시 겨울인턴여부를 받습니다.
- 모집의뢰서 리스트 조회 겨울인턴 필터를 추가했어요
- ApplyRecruitmentUseCase
- %QueryRecruitmentsUseCase
close #457

🔗 :: (#457) 겨울인턴 필터 추가

---

jobis-application/src/main/java/team/retum/jobis/common/util/StringUtil.java

- blank 처리
- StringUtill
close #466

🔗 :: (#466) 모집의뢰 조회 필터 에러

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java

🔗 :: (#468) 존재여부 판단에 winter Intern 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CompanyQueryApplicationsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java

- 지원서에 전송 상태를 추가했습니다.
- ApplicationStatus
close #

🔗 :: (#470) 지원서 전송 상태 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

- 쿼리 변경
- containsCode()
close #475

🔗 :: (#475) 페이지 개수 문제

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryRejectionReasonResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryRejectionReasonUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ReapplyUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RecreateApplicationUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- 재지원 api 만들었어용
- RecreateApplicationUseCase
close #471

🔗 :: (#471) 재지원 api

---

jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CompanyQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryMyApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java

- 페이징이 없어서 추가
- TeacherQueryApplicationsUseCase
close #487

🔗 :: (#487) 선생님 지원서 리스트 조회 페이징

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryEmploymentCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentCountUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java

🔗 :: (#489) 지원한 학생수 버그

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

- 학생 리스트 조회시 종료된 모집의뢰서도 함께 조회하는것을 확인하였습니다.
- where 절에 recruiting 상태인 모집의뢰서만 조회하게 추가하였습니다.
- StudentQueryRecruitmentsUseCase
close #491

⚙️ :: (#491) 모집중인것만 조회

---

jobis-application/src/main/java/team/retum/jobis/domain/auth/dto/TokenResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/model/PlatformType.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/model/RefreshToken.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/CommandRefreshTokenPort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/JwtPort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/QueryRefreshTokenPort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/RefreshTokenPort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/TokenReissueUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/dto/StudentSignUpRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/user/dto/LoginRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/LoginUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/persistence/RefreshTokenPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/persistence/entity/RefreshTokenEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/persistence/mapper/RefreshTokenMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/persistence/repository/RefreshTokenRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/AuthWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/StudentSignUpWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/dto/request/LoginWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RedisConfig.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/jwt/JwtTokenAdapter.java

- 리이슈가 안되서 로그아웃 되는 현상을 해결하기위해 이렇게 했읍니다.
- RefreshToken
close #499

🔗 :: (#499) refreshToken 플랫폼별 생성

---

.github/CODEOWNERS
jobis-infrastructure/src/main/resources/banner.txt

🔗 :: (#505) spring banner custom

---

jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/ChangeContractDateUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeFieldTrainDateUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/DeleteApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryRejectionReasonUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitmentUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/acceptance/presentation/dto/request/ChangeContractDateWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/dto/request/ChangeFieldTrainDateWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/web/WebSecurityConfig.java

- 날짜 검증 if문 -> validation 어노테이션으로 변경
- UseCase 안의 도메인 검증 로직 도메인 안으로 이동, equals로 비교하도록 변경
- 상태 검증 if문 -> where절로 조회하도록 변경
close #503

🔗 :: (#503) 자잘한 리팩토링

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/presentation/BookmarkWebAdapter.java

🔗 :: (#508) 북마크할 때 모집의뢰서 변경 안되는 문제 발생

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

- Security Config 오타수정
- SecurityConfig
close #512

🔗 :: (#512) 오타수정

---

jobis-application/src/main/java/team/retum/jobis/domain/bookmark/spi/vo/StudentBookmarksVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/persistence/BookmarkPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/persistence/repository/vo/QueryStudentBookmarksVO.java

- 북마크 조회 API 수정
-
- GET /bookmarks
close #514

🔗 :: (#514) 북마크 조회시 기업로고 반환

---

jobis-application/src/main/java/team/retum/jobis/domain/notice/model/Notice.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/model/NoticeAttachment.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/NotificationNotFoundException.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/error/NotificationErrorCode.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeAttachmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/repository/NoticeJpaRepository.java

- notice entity mapping
-
- 
- 
close #510

🔗 :: (#510) notice entity mapping

---

jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/ChangeContractDateUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/RegisterCompanyResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/entity/BannerEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/repository/BannerJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetails.java

-  회사 user조인 제거
- 관련 api 수정
- companyentity
- registerCompanyUseCase
- ApplyRecruitmentUseCase
close #516

🔗 :: (#516) 회사 user조인 제거

---

jobis-application/src/main/java/team/retum/jobis/domain/banner/dto/CreateBannerRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/exception/BannerNotFoundException.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/exception/error/BannerErrorCode.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/model/Banner.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/model/BannerType.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/BannerPort.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/CommandBannerPort.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/CreateBannerUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/entity/BannerEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/mapper/BannerMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/repository/BannerJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/presentation/BannerWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/presentation/dto/CreateBannerWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- 배너 생성 api
- 
- createBannerUseCase
- 
close #520

🔗 :: (#520) 배너 생성 api

---

jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/CreateNoticeRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/request/CreateNoticeRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/AttachmentResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/exception/NoticeNotFoundException.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/exception/error/NoticeErrorCode.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/model/AttachmentType.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/model/Notice.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/model/NoticeAttachment.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/CommandNoticePort.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/NoticePort.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeAttachmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/NoticeWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/dto/CreateNoticeWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/dto/UpdateNoticeWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- 공지사항 생성 api
-
- 
- 
close #526

🔗 :: (#526) 공지사항 생성 api

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CheckCompanyExistsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CheckCompanyExistsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/CompanyJpaRepository.java

- 존재시 id반환 및 feign호출 안하도록 변경
- CheckCompanyExistsUseCase
close #531

🔗 :: (#531) 기업 계정 존재여부 확인 api 변경

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryMyApplicationsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/vo/ApplicationVO.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryMyApplicationsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/vo/QueryApplicationVO.java

🔗 :: (#538) 지원내역 조회 API 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java

- Optional로 감싸서 Null처리
- CompanyPersistenceAdapter
close #545

🔗 :: (#545) company detail 조회 예외처리

---

jobis-application/src/main/java/team/retum/jobis/domain/notification/dto/response/QueryNotificationsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Notification.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/QueryNotificationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/QueryNotificationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/ReadNotificationUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/NotificationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- 알림 리스트 조회 api
- 알림 읽음 api
- QueryNotificationsUseCase
- ReadNotificationUseCase
close #540

🔗 :: (#540) 알림 리스트 조회 api

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/model/Student.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- 모집의뢰서 상세조회에 북마크 여부, 지원가능 여부 추가
- QueryRecruitmentDetailUseCase
close #534

🔗 :: (#534) 모집의뢰서 상세조회에 북마크 여부, 지원가능 여부 추가하기

---

jobis-application/src/main/java/team/retum/jobis/domain/user/dto/SetDeviceTokenRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/user/model/User.java
jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/SetDeviceTokenUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/UserWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/dto/request/SetDeviceTokenWebRequest.java

- 디바이스 토큰 설정 api
- SetDeviceTokenUseCase
close #542

🔗 :: (#542) 디바이스 토큰 설정 api

---

jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/TokenReissueUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/dto/request/StudentSignUpRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/user/dto/request/LoginRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/LoginUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/AuthWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/StudentSignUpWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/dto/request/LoginWebRequest.java

- 토큰재발급, 로그인, 회원가입에 디바이스토큰 저장 추가
- TokenReissueUseCase
- StudentSignUpUseCase
- LoginUseCase
close #562

🔗 :: (#562) 토큰재발급, 로그인, 회원가입에 디바이스토큰 저장 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/TokenReissueUseCase.java

- anonymousUser
- 
- 
close #564

🔗 :: (#564) reissue 500

---

jobis-application/src/main/java/team/retum/jobis/domain/code/dto/request/CreateCodeRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/code/dto/response/CreateCodeResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
jobis-application/src/main/java/team/retum/jobis/domain/code/spi/CommandCodePort.java
jobis-application/src/main/java/team/retum/jobis/domain/code/spi/QueryCodePort.java
jobis-application/src/main/java/team/retum/jobis/domain/code/usecase/CreateCodeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/code/usecase/QueryCodesUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/repository/CodeJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/presentation/CodeWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/presentation/dto/CreateCodeWebRequest.java

- 코드 생성 api
- CreateCodeUseCase
close #560

🔗 :: (#560) 코드 생성 api

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml

🔗 :: (#566) cd 수정

---

jobis-infrastructure/build.gradle
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
jobis-infrastructure/src/main/resources/application.yml
jobis-infrastructure/src/main/resources/db/migration/V1__modify_is_public.sql

- flyway 적용
앞으로 DDL이 변경되는 PR을 올리는 경우 위의 버저닝 규칙에 맞게 /resoruces/db/migration 폴더에 sql파일을 작성해주시고 올려주세요
close #568

🔗 :: (#568) DB 마이그레이션 툴 적용

---

jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/AttachmentResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/QueryNoticeDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/model/NoticeAttachment.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/QueryNoticeDetailUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/NoticeWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- 공지사항 상세조회 api 추가
-
- 
- 
close #570

🔗 :: (#570) 공지사항 상세 조회

---

jobis-application/build.gradle
jobis-application/src/main/java/team/retum/jobis/common/util/StringUtil.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FirebaseConfig.java

- 기업 대표번호, 첨부파일 필드 추가
- file 읽는거 try-with resource로 변경
- random util 변경
- GET /compaines/my
- POST /auth/code
close #577

🔗 :: (#577) 기업 내 정보 조회 api 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java

- 사업자등록증, 첨부파일, 사업분야 변경
- PATCH /companies/{company-id}
close #579

🔗 :: (#579) 기업정보 수정 API변경

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#582) 공지사항 상세 조회 권한 부여

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryMyRecruitmentsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/MyAllRecruitmentsVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentAreaElement.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryMyAllRecruitmentsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

- 내 모집의뢰서 리스트 조회
- url 변경
- 
- 
close #576

🔗 :: (#576) 내 모집의뢰서 리스트 조회

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java

- 정규식 검사 수정
- recruitmentId넘기도록 수정
- 
- 
close #588

🔗 :: (#588) 모집의뢰서 생성, 수정 고침

---

jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/RecruitArea.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java

- 모집분야 중복되는 문제 해결
- UpdateRecruitAreaUseCase
close #590

🔗 :: (#590) 모집분야 중복문제

---

jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/entity/StudentEntity.java
jobis-infrastructure/src/main/resources/application.yml
jobis-infrastructure/src/main/resources/db/migration/V4__modify_school_number_unique_constraint.sql

- 지원 가능 여부를 입학년도로 구분
- 학번 unique 조건에 입학년도도 추가
- CreateApplicationService
close #598

🔗 :: (#598) 지원 가능 여부를 입학년도로 구분, 학번 unique 조건에 입학년도도 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/StudentQueryRecruitmentsResponse.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

🔗 :: (#600) 학생 모집의뢰서 조회 캐시 제거

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java

- bizRegistrationUrl, businessAreaCode 추가
- 
- 
close #606

🔗 :: (#606) 기업 상세 조회 response 필드 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java

🔗 :: (#604) 지원서 상태 이름 반환

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java

⚙️ :: (#608) 기업 정보 수정 수정될 필요 없는 필드 제거

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitAreaResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

- 모집의뢰서 상세 조회 시 지원한 기업 false 처리
- 자잘한 리팩토링
- 
- 
close #610

🔗 :: (#610) 모집의뢰서 상세 조회 시 지원한 기업 false 처리

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/presentation/CodeWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- 조인 수정
- cache condition 추가
- 
- 
close #

🔗 :: (#615) 조인 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/CommandBugReportPort.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/PublishBugReportEventPort.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/QueryBugReportPort.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/CreateBugReportUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/QueryBugReportDetailsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/QueryBugReportsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/BugReportPersistenceAdapter.java

🔗 :: (#624) bug 리펙토링

---

jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentCountUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/TokenReissueUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/CommandReviewPort.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryReviewPort.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/DeleteReviewUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewDetailUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/CommandStudentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/CommandVerifiedStudentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/StudentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/VerifiedStudentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentForgottenPasswordUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentPasswordUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentProfileUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/user/spi/CommandUserPort.java
jobis-application/src/main/java/team/retum/jobis/domain/user/spi/QueryUserPort.java
jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/LoginUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/SetDeviceTokenUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/VerifiedStudentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
jobis-infrastructure/src/main/resources/application.yml

🔗 :: (#629) User, Review, Student 리팩토링

---

jobis-application/src/main/java/team/retum/jobis/domain/notice/model/Notice.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/CommandNoticePort.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java

- 공지사항 작성 후 알림 송신 api
- resolved #628

🔗 :: (#628) 공지사항 작성 알림 송신

---

jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ReapplyUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationAttachmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
jobis-infrastructure/src/main/resources/application.yml
jobis-infrastructure/src/main/resources/db/migration/V2__application_attchament.sql

🔗 :: (#634) application attachment 구조 변경

---

jobis-application/src/main/java/team/retum/jobis/common/spi/WriteFilePort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/ExportRecruitmentHistoryResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ExportRecruitmentHistoryUseCase.java
jobis-infrastructure/build.gradle
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/paser/ExcelAdapter.java

🔗 :: (#614) 모집의뢰서 엑셀 출력

---

jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationMapper.java
jobis-infrastructure/src/main/resources/db/migration/V3__application_updated_at.sql

🔗 :: (#636) 지원서 updated_at 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ExportRecruitmentHistoryUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/resources/application.yml

🔗 :: (#641) 어드민 모집의뢰서 페이징 없는 조회 API 

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/ExportRecruitmentHistoryResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitAreaUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ExportRecruitmentHistoryUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/acceptance/persistence/mapper/AcceptanceMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/persistence/mapper/BookmarkMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/mapper/BugReportMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/RecruitAreaCodeId.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/repository/CodeJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/mapper/NotificationMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitAreaPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitAreaEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitAreaMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/QnAMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/ReviewMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/PortfolioMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/StudentMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/teacher/persistence/mapper/TeacherMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/repository/UserJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

🔗 :: (#639) Mapper 리펙토링

---

jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/CommandAuthCodePort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/CommandRefreshTokenPort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/QueryAuthCodePort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/spi/QueryRefreshTokenPort.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/TokenReissueUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/VerifyAuthCodeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/CommandBannerPort.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/QueryBannerPort.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/CreateBannerUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/DeleteBannerUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/QueryBannersUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/TeacherQueryBannersUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentForgottenPasswordUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/persistence/AuthCodePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/persistence/RefreshTokenPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FirebaseConfig.java

🔗 :: (#645) Auth, Banner 리팩토링

---

jobis-application/src/main/java/team/retum/jobis/domain/acceptance/spi/CommandAcceptancePort.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/spi/QueryAcceptancePort.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/RegisterEmploymentContractUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/TeacherQueryFieldTraineesAndContractWorkersUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/acceptance/persistence/AcceptancePersistenceAdapter.java

🔗 :: (#644) Acceptance 리팩토링

---

jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/CancelFieldTraineesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/RegisterEmploymentContractUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/RegisterFieldTraineeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/TeacherQueryFieldTraineesAndContractWorkersUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeFieldTrainDateUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CompanyQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/DeleteApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryMyApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryPassedApplicationStudentsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryRejectionReasonUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ReapplyUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java

🔗 :: (#643) Application 리팩토링

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ExportRecruitmentHistoryUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

🔗 :: (#649) 페이징 없는 모집의뢰서 조회 API 채용형, 채험형 필터 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/banner/dto/request/CreateBannerRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/model/Banner.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/vo/BannerVO.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/vo/TeacherBannersVO.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/CreateBannerUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/entity/BannerEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/mapper/BannerMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/repository/vo/QueryBannerVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/repository/vo/QueryTeacherBannersVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/presentation/BannerWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/presentation/dto/CreateBannerWebRequest.java

🔗 :: (#633) 배너 엔티티 detailId 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/CompanyFilter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/resources/application.yml
jobis-infrastructure/src/main/resources/db/migration/V4__add_detail_id.sql

🔗 :: (#652) 기업 조회 paging optional 처리

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/RecruitmentFilter.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

🔗 :: (#655) 병특 필터링 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

🔗 :: (#658) 기술스택 필터링 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/ApplicationCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#661) 모집의뢰서, 기업, 지원서 총 개수

---

jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherDeleteApplicationUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#663) 어드민 지원서 삭제

---

jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java

🔗 :: (#667) 로 -> 으로

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java

🔗 :: (#669) 학생 회사 리스트 조회 버그

---

jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java

리뷰를 진행중, 탈락됨일 때도 작성 가능하게 수정
리뷰를 여러개 작성할 수 있도록 수정
- resolved #665

🔗 :: (#665) 리뷰 작성 예외처리 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#674) 지원서 엔드포인트 변경

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java

🔗 :: 기업 리스트 최근 의뢰년도로 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java

🔗 :: (#678) 진행중 상태일때 알림 안가게 변경

---

jobis-application/src/main/java/team/retum/jobis/common/spi/WriteFilePort.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/ExportCompanyHistoryResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/ExportCompanyHistoryUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/paser/ExcelAdapter.java

🔗 :: (#666) 기업 엑셀 출력 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java

🔗 :: (#680) 합격 통지 문구 변경

---

jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java

🔗 :: (#683) 코드 리팩토링

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/RecruitmentFilter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

🔗 :: (#682) offset 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/CommandBannerPort.java
jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/UpdateBannerStatusUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/BannerScheduler.java

🔗 :: (#688) 배너 시간 로직 수정

---

.github/workflows/build.yml

🔗 :: (#694) bucket env 추가

---

.github/workflows/build.yml
jobis-infrastructure/src/main/resources/application-dev.yml
jobis-infrastructure/src/main/resources/application-local.yml
jobis-infrastructure/src/main/resources/application-prod.yml
jobis-infrastructure/src/main/resources/application.yml

🔗 :: (#691) yml 파일 분리

---

jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeAllTopicsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/UnsubscribeAllTopicsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🧩 :: (#697) 알림 전체 구독/해제 api

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#700) 엔드포인트 수정

---

jobis-infrastructure/src/main/resources/db/migration/V5__create_interest.sql

🔗 :: (#709) flyway 스크립트 작성

---

jobis-application/src/main/java/team/retum/jobis/domain/intern/model/WinterIntern.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/spi/QueryWinterInternPort.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/QueryIsWinterInternUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/ToggleWinterInternUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/intern/persistence/WinterInternPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/intern/persistence/entity/WinterInternEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/intern/presentation/WinterInternWebAdapter.java

🔗 :: (#717) 겨울인턴 메서드명 및 로직 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/BannerScheduler.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/InterestedRecruitmentScheduler.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/RecruitmentScheduler.java

🔗 :: (#719) 스케줄러에 주석처리

---

jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandTopicSubscriptionPort.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/TopicSubscriptionPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/repository/TopicSubscriptionJpaRepository.java

🔗 :: (#722) 알림 기본값 넣어줌

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#726) 겨울인턴 여부 조회 학생 권한 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/dto/request/SendAuthCodeWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/StudentSignUpWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/UpdateForgottenPasswordWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

- 정규식 조건 ^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
- resolved #728

🔗 :: (#728) 기업 이메일 정규식 확인 코드 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/util/ImageProperty.java

 🔗 :: (#732) 기본 이미지 변경

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CheckRecruitmentExistsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗: (#734) 회사별 모집의뢰서 확인 로직 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java

🔗 :: (#736) 사업자 등록증 not null로 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/RecruitAreaWebRequest.java

🔗 :: (#738) 500 에러 -> 400 bad request

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java

🔗 :: (#740) 전화번호 validation 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

🔗 :: (#742) 파일 업로드 시 특수문자 방지

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java

🔗 :: (#745) 최소 성적 최댓값 설정

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

🔗 :: (#746) 파일명 정규식 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java

🔗 :: (#744) 모집의뢰서 수정 validation 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandNotificationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/NotificationPersistenceAdapter.java

🔗 :: (#749) 회원가입시 topic 자동 구독

---

jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java

 🔗 :: (#752) 모집의뢰서 지원 비활성화

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java

🔗 :: (#759) 모집의뢰 상세 조회 버그 해결

---

jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java

🔗  :: (#756) 기업등록 시 user 생성

---

jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/DeviceTokenNotFoundException.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java

🔗 :: (#757) 토픽 구독 예외처리 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java

🔗 :: (#762) 대표번호 validiation 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java

🔗 :: (#766) 토픽 구독 예외처리 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V11_modify_company_column_length.sql

🔗 :: (#770) 컬럼 길이 줄이기

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V14__add_column_in_company.sql

🔗 :: (#781) 회사 지점 여부 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/TeacherRecruitmentVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryTeacherRecruitmentsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V13__add_hire_convertible.sql

리스트 조회
상세 조회
모집의뢰서 수정
- resolved #774

 🔗 :: (#774) isConvertible 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentRateUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/EmploymentRatesResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java

🔗 :: (#783) 반별 학생 수 조회 로직 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V16__modify_column_name_in_company.sql

🔗 :: (#788) 컬럼명 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/TeacherRecruitmentVO.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryTeacherRecruitmentsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V17__rename_column_in_company.sql

🔗 :: (#790) 컬럼명 통일

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java

🔗 :: (#792) isHireConvertible 제거

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java

🔗 :: (#798) 겨울인턴 여부 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/ApplicationFilter.java
jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/ApplicationCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

기업
모집의뢰서
지원서
지원서 페이징
- resolved #

🔗 :: (#800) 총개수 조회 api 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/ApplicationCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentCountResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java

🔗 :: (#802) 총개수 버그 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/CompanySignInUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/AuthWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/dto/request/CompanySignInWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/entity/UserEntity.java
jobis-infrastructure/src/main/resources/db/migration/V20__modify_column_in_user.sql

🔗 :: (#805) 기업 로그인 시 비밀번호 제거

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/StudentQueryRecruitmentsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/StudentRecruitmentVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryStudentRecruitmentsVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V22__modify_column_in_recruitment.sql

🔗 :: (#810) military null 처리

---

jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Topic.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/WinterInternRegisteredEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java

🔗 :: (#820) 알림 타입 및 로직 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java

page가 null 일 경우 추가
- resolved #823

🔗 :: (823) 지원서 필터링 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java

🔗 :: (#826) 대표번호 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java

🔗 :: (#828) phonw -> phone

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentExistsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CheckRecruitmentExistsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

🔗 :: (#834) response 변경

---

jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java

 🔗 :: (836) 디바이스 토큰 플랫폼 타입 설정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

🔗 :: (#838) 모집중인 상태만 체크

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

🔗 :: (#842) 채용인원 쿼리 변경

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/util/ImageProperty.java

🔗 :: (844) 기본 이미지 변경

---

jobis-application/src/main/java/team/retum/jobis/domain/acceptance/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java

🔗 :: (#846) 기본생성자 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/dto/request/CreateApplicationWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/file/presentation/dto/CreatePreSignedUrlWebRequest.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java

🔗 :: (848) 지원서 버그 픽스

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/dto/CreateNoticeWebRequest.java

공지 파일을 null 가능하도록 변경했습니다
- resolved #850

🔗 :: (#850) 공지 파일 nullable로 변경

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/ApplicationFilter.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java

🔗 :: (858) 지원서 페이징 제거

---

jobis-application/src/main/java/team/retum/jobis/domain/application/event/SingleApplicationStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java

🔗 :: (#857) 반려시 알림 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentRateUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java

🔗 :: (864) 취업 현황 코드 리팩

---

jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/EmploymentRatesResponse.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java

🔗 :: (868) 현재 취업률 조회 api 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java

🔗 :: (#878) 겨울인턴 일때만 알림 발송

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherRegisterCompanyUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/TeacherRegisterCompanyWebRequest.java

- TeacherRegisterCompanyWebRequest 이름 수정
- resolved #882

🔗 :: (#882) WebRequest 이름 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java

🔗 :: (#884) rabbitmq 메세지 컨버터 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java

🔗 :: (#886) 라우팅 키 이름 통일

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java

https://www.programmersought.com/article/6243566022/
문서 참고
- resolved #894

 🔗 :: (#887) 역직렬화 컨버터 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java

- `학년 기반` 조회 -> `입학년도 - 현재 년도` 조회
- resolved #901

🔗 :: (#901) 취업률 조회 쿼리 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/application/event/ApplicationsStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/application/event/SingleApplicationStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternToggledEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/ToggleWinterInternUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/event/NoticePostedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/InterestedRecruitmentEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/RecruitmentStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherChangeRecruitmentStatusUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java

🔗 :: (#903) rabbitmq 메세지 형식 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitAreaEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/RecruitAreaWebRequest.java

🔗 :: (#887) 고용인원 수 변경  

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherRegisterCompanyUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java

🔗 :: (#905) 모집의뢰서 종료 시 추가 등록

---

jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherRegisterCompanyUseCase.java

- accountId 생성 로직 개선
- resolved #889

🔗 :: (#889) accountId 생성 로직 개선

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/RecruitArea.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitAreaEntity.java

🔗 :: (#910) orphanRemoval 관계 설정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java

쿼리에 겨울인턴인 학생들도 포함되어 있기에 이 부분을 수정합니다
- resolved #914

 🔗 :: (#914) 겨울 인턴 포함 여부 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java

3학년, 겨울인턴 조건 추가
- resolved #916

🔗 :: (#916) 3학년 조건 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/application/event/ApplicationsStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/application/event/SingleApplicationStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternToggledEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/ToggleWinterInternUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/event/NoticePostedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/InterestedRecruitmentEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/RecruitmentStatusChangedEvent.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherChangeRecruitmentStatusUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java

🔗 :: (#920) 알림 발송 객체 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/entity/NotificationEntity.java
jobis-infrastructure/src/main/resources/db/migration/V27__modify_column_in_notification.sql

🔗 :: (#922) 컬럼 최대 글자수 변경

---

jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeAllUserUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/user/spi/QueryUserPort.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/repository/UserJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/FcmScheduler.java
jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java

* 매 4월 2일 9시 15분에 실행
* deviceToken을 가지고 있는 유저들의 모든 토픽구독 상태를 true로 변경
- resolved #928

🔗 :: (#928) fcm 전체 구독 스케줄러 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java

🔗 :: (#919) 나의 지원서 조회 수정

---

jobis-infrastructure/src/main/resources/db/migration/V29__modify_column_in_company.sql

* flyway 에서 디폴트 이미지 넣는 부분 추가
- resolved #931

🔗 :: (#931) flyway 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java

작년 3학년을 제외한 올해 3학년의 취업률만 보이도록 수정
- resolved #937

🔗 :: (#937) 취업률 조회 로직 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/interest/dto/response/StudentQueryInterestsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/QueryMyInterestsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/presentation/InterestWebAdapter.java

🔗 :: (#942) 관심 분야 조회 시 학생 이름 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/code/spi/QueryCodePort.java
jobis-application/src/main/java/team/retum/jobis/domain/interest/dto/request/ToggleInterestRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/interest/exception/InvalidCodesException.java
jobis-application/src/main/java/team/retum/jobis/domain/interest/exception/error/InterestErrorCode.java
jobis-application/src/main/java/team/retum/jobis/domain/interest/spi/QueryInterestPort.java
jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/ToggleInterestUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/persistence/InterestPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/presentation/InterestWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java

- 관심분야 토글 api의 매개변수를 codeIds로 통일하였습니다.
- 관심 분야 토글 API에서 잘못된 요청 시 발생하는 500 에러를 상황에 맞는 적절한 예외 처리로 변경하였습니다.
- #945

🔗 :: (#945) 관심분야 잘못된 요청에 대한 예외 처리 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

- 학생 모집 의뢰서 조회시 필터링 오류를 수정
- resolved #935

🔗 :: (#935) 필터링 조건 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/RecruitmentScheduler.java

* 모집의뢰서에서 상시모집상태일때 (startTime, endTime 이 null 일때) 처리 로직 추가
* 북마크한 모집의뢰서 마감 안됬을시에 알림 가는 버그 수정
- resolved #941

🔗 :: (#941) 모집의뢰서 스케줄러 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/RecruitmentScheduler.java

🔗 : (#948) 모집의뢰서 스케줄러 시간 변경

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java

- 필터링 적용 오류 수정
- resolved #935

🔗 :: (#935) 모집의뢰서 조회 필터링 적용 오류 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/StudentRecruitmentFilter.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- tech_code, job_code 적용시 발생 오류 수정
- resolved #935

🔗 :: (#935) tech, job code 조회 필터링 오류 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- null을 Long으로 파싱하기 전 한번 더 nullCheck
- resolved #953

🔗:: 953 null parse error

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- 공백 문자 파싱 오류 수정
- resolved #955

🔗 :: (#955) 공백 문자 파싱 오류 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java

- null 문자 파싱 오류  수정
- resolved #956

🔗 :: (#956) null 문자 파싱 오류 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/acceptance/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java

- 레디스 역직렬화 오류 해결을 위한 생성자 추가
- #960

🔗 :: (#960) 레디스 역직렬화 오류 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/application/dto/request/RejectionAttachmentRequest.java
jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryRejectionReasonResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationRejectionAttachment.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryRejectionReasonUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationRejectionAttachmentEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationMapper.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/dto/request/RejectApplicationWebRequest.java
jobis-infrastructure/src/main/resources/db/migration/V31__create_application_rejeaction_attachment.sql

* ApplicationRejection 추가
* 지원 반려 api 에 파일첨부 가능하도록 수정
* 반려사유 볼시 첨부된 파일 볼수있도록 수정
- resolved #963

🔗 :: (#963) 지원 반려, 반려사유 API 에 파일첨부 기능 추가

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/web/WebSecurityConfig.java

도메인 주소가 .monster로 바뀜에 따라 Cors 허용 주소 변경
- resolved #973

 🔗 :: (#973) CORS 도메인 주소 변경

---

jobis-infrastructure/src/main/resources/db/migration/V32__create_view_log.sql

🔗 :: (#984) flyway 수정

---

jobis-application/src/main/java/team/retum/jobis/domain/review/model/InterviewLocation.java
jobis-application/src/main/java/team/retum/jobis/domain/review/model/InterviewType.java
jobis-application/src/main/java/team/retum/jobis/domain/review/model/Review.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/entity/ReviewEntity.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/ReviewMapper.java
jobis-infrastructure/src/main/resources/db/migration/V33__add_review_interview_fields.sql
jobis-infrastructure/src/main/resources/db/migration/V34__add_review_constraint.sql

- 리뷰 컬럼 추가
- flyway
- resolved #989

🔗 :: (#989) 리뷰 엔티티 수정 및 flyway

---

jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java

🔗 :: (#994) 후기 작성 가능 기업 지원서 상태 추가

---

jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QnAResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QueryReviewDetailResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryReviewPort.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/QnAVO.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/ReviewDetailVO.java
jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/ReviewVO.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewDetailUseCase.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryQnAVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryReviewDetailVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryReviewVO.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/ReviewWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

🔗 :: (#1002) 리뷰 상세 조회 api

---

jobis-application/src/main/java/team/retum/jobis/domain/review/dto/QnAElement.java
jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QueryReviewQuestionsResponse.java
jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewQuestionsUseCase.java
jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/ReviewWebAdapter.java
jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java

* 리뷰 옵션 조회 api 엔드포인트 수정
* useCase 수정
* 안쓰는 Element 삭제
* 기존 options 네이밍 -> quetions 로 변경
- resolved #1015

🔗 :: (#1015) 리뷰옵션 조회 api 수정

---

jobis-infrastructure/src/main/resources/db/migration/V32__create_view_log.sql

- flyway 이름 중복 오류 수정
- resolved #1022

🔗 :: (#1022) flyway 이름 중복 오류 수정

---

jobis-infrastructure/src/main/resources/db/migration/V32__create_view_log.sql
jobis-infrastructure/src/main/resources/db/migration/V40__drop_view_log.sql
jobis-infrastructure/src/main/resources/db/migration/V41__create_view_log_again.sql

🔗 :: (#1024) flyway 수정

---

jobis-infrastructure/src/main/java/team/retum/jobis/global/web/WebSecurityConfig.java

🔗 :: (#1033) CORS 요청 경로 허용
